version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '18:02'
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '18:02'
    open-pull-requests-limit: 10
