on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
         gh issue edit $ISSUE_URL --add-label "triage"
         gh issue comment $ISSUE_URL --body "Hi! <br> Im Github App / Bot! <br> Thanks for submitting issue! <br> This issue is now on status 'triage' <br> Note: In this account is owner too."
